// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("checkInterval" in $$source)) {
            /**
             * intervalo en segundos
             * @member
             * @type {number}
             */
            this["checkInterval"] = 0;
        }
        if (!("retentionDays" in $$source)) {
            /**
             * días de retención de datos
             * @member
             * @type {number}
             */
            this["retentionDays"] = 0;
        }
        if (!("sites" in $$source)) {
            /**
             * @member
             * @type {Site[]}
             */
            this["sites"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sites" in $$parsedSource) {
            $$parsedSource["sites"] = $$createField2_0($$parsedSource["sites"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class Site {
    /**
     * Creates a new Site instance.
     * @param {Partial<Site>} [$$source = {}] - The source object to create the Site.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Site instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Site}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Site(/** @type {Partial<Site>} */($$parsedSource));
    }
}

export class SiteDetail {
    /**
     * Creates a new SiteDetail instance.
     * @param {Partial<SiteDetail>} [$$source = {}] - The source object to create the SiteDetail.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["statusCode"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["responseTime"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastChecked"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = "";
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SiteDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteDetail(/** @type {Partial<SiteDetail>} */($$parsedSource));
    }
}

export class StatusCheck {
    /**
     * Creates a new StatusCheck instance.
     * @param {Partial<StatusCheck>} [$$source = {}] - The source object to create the StatusCheck.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("siteName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["siteName"] = "";
        }
        if (!("siteUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["siteUrl"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "up", "down"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("statusCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["statusCode"] = 0;
        }
        if (!("responseTime" in $$source)) {
            /**
             * en milisegundos
             * @member
             * @type {number}
             */
            this["responseTime"] = 0;
        }
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["checkedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusCheck}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusCheck(/** @type {Partial<StatusCheck>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Site.createFrom;
const $$createType1 = $Create.Array($$createType0);
